name: Build
on:
  push:

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Cache Nuget
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
      - name: Build executable
        run:
          dotnet publish PacsRefetch/PacsRefetch.csproj -o lin -r linux-x64 -p:PublishSingleFile=true --self-contained true  -p:PublishReadyToRun=true -nologo
