name: Build
on:
  push:

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      - name: Build executable
        run:
          dotnet publish PacsRefetch/PacsRefetch.csproj -o lin -r linux-x64 -nologo
